# Generated by Django 3.1.2 on 2021-02-06 14:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('name', models.TextField()),
                ('utr_id', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.TextField()),
                ('homePhone', models.IntegerField()),
                ('mobilePhone', models.IntegerField()),
                ('city', models.TextField(max_length=30)),
                ('country', models.TextField(max_length=30)),
                ('age', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('utr', models.IntegerField(validators=[django.core.validators.MaxValueValidator(16), django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='HighSchoolPlayer',
            fields=[
                ('player_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.player')),
                ('school', models.TextField(max_length=30)),
                ('graduating', models.IntegerField()),
                ('recruitingWebsite', models.URLField(max_length=50)),
                ('ustaRanking', models.IntegerField()),
                ('itfRanking', models.IntegerField()),
            ],
            bases=('main.player',),
        ),
        migrations.CreateModel(
            name='ProPlayer',
            fields=[
                ('player_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.player')),
                ('atpRanking', models.IntegerField()),
                ('totalSalary', models.IntegerField()),
                ('monthsOnTour', models.IntegerField()),
            ],
            bases=('main.player',),
        ),
    ]
